env:
  browser: true
  es2021: true
  jquery: true
  node: true
extends:
  - standard
  - 'plugin:vue/vue3-recommended'
parserOptions:
  sourceType: module
rules:
  'dot-notation':
    - error
    - allowPattern: '^[A-Z]'
  'object-shorthand':
    - error
    - consistent-as-needed
  'vue/html-closing-bracket-spacing': 0
  'vue/max-attributes-per-line': 0
  'vue/multi-word-component-names': off
  'vue/singleline-html-element-content-newline': 0
