env:
  browser: true
  es2021: true
  jquery: true
  node: true
extends:
  - standard
  - 'plugin:vue/vue3-recommended'
parserOptions:
  sourceType: module
rules:
  'vue/html-closing-bracket-spacing': 0
  'vue/max-attributes-per-line': 0
  'vue/singleline-html-element-content-newline': 0

