# Hack per https://github.com/yarnpkg/berry/issues/4014
changesetBaseRefs: ["HEAD"]

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
