name: Build
on: [ push, pull_request, release, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js for publishing to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          # TODO: is this still needed with yarn v3?
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check style
        run: yarn lint

      - name: Build
        run: yarn build

      # TODO: tests

      - name: Upload distribution
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**

      - name: Delete latest build package if present
        if: github.event_name == 'push'
        continue-on-error: true
        uses: actions/delete-package-versions@v3
        with:
          package-name: galc-ui
          # ignore-versions: '^(?!0\\.0\\.0).+$'
          num-old-versions-to-delete: 99

      - name: Publish latest build
        if: github.event_name == 'push'
        run: |
          yarn version 0.0.0 --immediate
          yarn npm publish --tag @"${GITHUB_SHA:0:7}"
        env:
          YARN_NPM_PUBLISH_REGISTRY: 'https://npm.pkg.github.com'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish released package
        if: github.event_name == 'release' && github.event.action == 'created'
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
