name: Build
on: [ push, pull_request, release, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js for publishing to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check style
        run: yarn lint

      - name: Build
        run: yarn build

      # TODO: tests

      - name: Upload distribution
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**

      - name: Delete latest build package if present
        if: github.event_name == 'push'
        continue-on-error: true
        uses: actions/delete-package-versions@v3
        with:
          # TODO: Determine this programmatically
          package-name: galc-ui
          # TODO: something less janky
          # NOTE: There's no way to specify a specific version name -- see https://github.com/actions/delete-package-versions/issues/61
          ignore-versions: '^(?!0\\.0\\.0).+$'
          min-versions-to-keep: 0


      - name: Publish latest build
        if: github.event_name == 'push'
        run: yarn publish --new-version 0.0.0 --no-git-tag-version --tag @"${GITHUB_SHA:0:7}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish released package
        if: github.event_name == 'release' && github.event.action == 'created'
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
