name: Build
on: [ push, pull_request, release, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js for publishing to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check style
        run: yarn lint

      - name: Build
        run: yarn build

      # TODO: tests

      - name: Upload distribution
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**

      - name: Publish package
        if: github.event_name == 'release' && github.event.action == 'created'
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
