name: Build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js for publishing to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Check style
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Upload build output
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**

      # TODO: something much less janky - probably publishing a package for each commit isn't what we want
      - name: Get version from package.json
        run: |
          PACKAGE_VERSION=$(node -pe "require('./package.json').version")
          echo "::set-output NAME=PACKAGE_VERSION::$PACKAGE_VERSION"
        id: package-version

      - name: Set temporary version
        run: |
          TEMP_VERSION=${{ steps.package-version.outputs.PACKAGE_VERSION}}-${{ github.sha }}
          yarn version --no-git-tag-version --new-version "${TEMP_VERSION}"

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
